### ISSUE TITLE
png transparency support?

### ISSUE THREAD

**Issue by niamu** [larshall/xbtfextractor#1]
I notice that you have gif transparency listed as not supported, but I seem to be having problems with png transparency. Or is this issue related to the build of libsquish?

Thanks a lot for this project. It is now a part of my toolkit.

**Comment by niamu** [comment]
After a little more research, it seems that the files I'm extracting have the alpha channel intact, but the colour values are off. I have read that there was an issue in libsquish which had DXT outputting BGRA instead of RGBA. I think that may be the issue I'm having now as images that are supposed to be green are displaying as blue.

I'm currently investigating to see if I can make the adjustments necessary to try to flip the RGB values on extraction to test if that is the issue.

**Comment by niamu** [comment]
It is definitely an issue of the colour channels being swapped. Converting the image from BGRA to RGBA fixes this problem. Sorry, I can't find a way to patch this myself.

Thanks again for this tool!

**Comment by larshall** [comment]
Hi niamu,
Thanks for using it! :)
If you send me the file you are trying to extract, I will try to hunt the bug (if it's in xbtfextractor) or try to find a some kind of workaround (if it is in libsquish or elsewhere).

/Lars

**Comment by niamu** [comment]
I was extracting the contents of [this skin's texture.xbt](https://github.com/downloads/MartijnKaijser/xbmc/skin.lightbox.zip):

The tricky part is when you realize that some images are BGR and others are RGB. So it's not clear which images need attention after extraction.

[libsquish that is packaged with XBMC](https://github.com/xbmc/xbmc/blob/master/lib/libsquish/squish.cpp) seems to be able to detect whether the image is in BGR or not with flags. You can see it on line 128 in action (if I'm reading it correctly). So perhaps you just need to pass the appropriate flags to libsquish and it will handle things?

**Comment by larshall** [comment]
Thanks!
You are right. I have fixed the RGB/BGR conversion when compresses png files.
I still need to check it when compressing jpeg files. So for now it's only fixed for png files.
Are the images correct now? They do look a lot better than before :)

**Comment by niamu** [comment]
The images are perfect now, thanks! If I had known you would be this responsive, I wouldn't have bothered writing my own script to cycle the colour channels myself to fix the extracted images. :P
