### ISSUE TITLE
BGR JPG compression

### ISSUE THREAD

**Issue by niamu** [larshall/xbtfextractor#2]
I just thought I'd offer the little bit of knowledge I've been able to dig up regarding the BGR/RGB issue with JPG compression.

If you are using the libjpeg-turbo library, there are apparently JCS_EXT_BGR and JCS_EXT_BGRX colorspaces available.

I attempted to apply a patch myself, but I don't think I was able to figure out how to compile xbtfextractor for libjpeg-turbo.

I thought I could insert something like this after line 432:

``` c
if (frame.format == XB_FMT_A8R8G8B8)
    jpeg.in_color_space = JCS_EXT_BGR;
```

Since I couldn't figure out how to compile with libjpeg-turbo, I never did get to test that solution. I'm also not a C++ programmer, but hopefully it's helpful in some way.

**Comment by larshall** [comment]
Great! Thanks for your help!
I've added your fix. I have tested it with the previous skin you provided and can I definitely see the difference with the jpegs :)

If you wish to use libjpeg-turbo (Without overwriting the default libjpeg) you can do the following: (If you use Debian or Ubuntu or any other Debian derivative)
Download and install libjpeg-turbo debian package from here: http://sourceforge.net/projects/libjpeg-turbo/files/

Add the following lines to your $HOME/.bashrc:
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/opt/libjpeg-turbo/include/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/libjpeg-turbo/lib/

Restart your terminal
Recompile xbtfextractor (make clean; make)

**Comment by niamu** [comment]
Awesome! Thanks for the info on compiling with libjpeg-turbo!
